import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const matieresStyles = StyleSheet.create({
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width,
    height,
    backgroundColor: "#6c63ff",
  },
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  header: {
    width: "100%",
    alignItems: "center",
    paddingTop: 70,
    paddingBottom: 20,
    backgroundColor: "#6c63ff",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#ddd",
    marginTop: 5,
    textAlign: "center",
  },
  tabs: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#fff",
    width: "100%",
    paddingVertical: 14,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  tabText: {
    fontSize: 16,
    color: "#999",
  },
  activeTabText: {
    color: "#000",
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  cardContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 20,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
    width: "100%",
    marginTop: 10,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 80,
    paddingHorizontal: 15,
    overflow: "hidden",
  },
  scrollContent: {
    paddingBottom: 100,
    paddingHorizontal: 10,
  },
  cardsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingBottom: 100,
    paddingHorizontal: 1,
    marginTop: 20,
  },
  subjectCard: {
    width: "48%",
    height: 120,
    backgroundColor: "#fff",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardImage: {
    width: 60,
    height: 60,
    resizeMode: "contain",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#222",
    textAlign: "center",
    marginTop: 10,
  },
  cardSubtitle: {
    fontSize: 14,
    fontWeight: "400",
    color: "#666",
    marginTop: 2,
    textAlign: "center",
  },
  navbarContainer: {
    position: "absolute",
    bottom: 34,
    width: "100%",
    alignItems: "center",
  },
  footerBlock: {
    width: "100%",
    height: 50,
    backgroundColor: "#fff",
  },
});
