import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const recommandationStyles = StyleSheet.create({
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width,
    height,
    backgroundColor: "#6c63ff",
  },
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  header: {
    width: "100%",
    alignItems: "center",
    paddingTop: 100,
    paddingBottom: 20,
    backgroundColor: "#6c63ff",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#ddd",
    marginTop: 5,
    textAlign: "center",
  },
  tabs: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#fff",
    width: "100%",
    paddingVertical: 14,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  tabText: {
    fontSize: 13,
    color: "#999",
  },
  activeTabText: {
    color: "#6c63ff",
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  cardContainer: {
    position: "absolute",
    top: 200, // 👈 même valeur partout pour aligner les cartes
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 20,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
    zIndex: 0,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 80,
    paddingHorizontal: 15,
    overflow: "hidden",
  },
  scrollContent: {
    paddingBottom: 100,
    alignItems: "center",
  },
  stackContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 30,
    gap: 26,
  },
  recoCard: {
    width: "90%",
    paddingVertical: 30,
    paddingHorizontal: 20,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  recoTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#222",
    textAlign: "center",
  },
  recoSubtitle: {
    fontSize: 14,
    color: "#666",
    marginTop: 5,
    textAlign: "center",
  },
  navbarContainer: {
    position: "absolute",
    bottom: 34,
    width: "100%",
    alignItems: "center",
  },
  footerBlock: {
    width: "100%",
    height: 50,
    backgroundColor: "#fff",
  },
});
